name: Linter
on: [push, pull_request]
jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install modules
        run: yarn
      - name: Install example
        run: yarn bootstrap-linux
      - name: Lint
        run: yarn lint
